name: 'CloudFormation Deploy Action Ubuntu Jammy'
description: 'Deploy AWS CloudFormation Stack for  Ubuntu Jammy'
branding:
  icon: 'upload-cloud'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
